# import dependencies
from typing import Iterable, Any

from tcod.context import Context
from tcod.console import Console
from tcod.map import compute_fov

from entity import Entity
from game_map import GameMap # type: ignore
from input_handlers import EventHandler

# manages the current state of the game
class Engine:

    # initialize engine with a set of entities, an event handler, and the player entity
    def __init__( self, event_handler: EventHandler, game_map: GameMap, player: Entity ):

        self.event_handler = event_handler
        self.game_map = game_map
        self.player = player
        self.update_fov()

    # handle moves for enemy entities
    def handle_enemy_turns( self ) -> None:

        for entity in self.game_map.entities - { self.player }:

            print( f"the {entity.name} is eating a banana" )

    # handle events generated by the user
    def handle_events( self, events: Iterable[ Any ] ) -> None:

        # event loop
        for event in events:

            # initialize action with event handler
            action = self.event_handler.dispatch( event )

             # if no action is detected, continue
            if action is None:

                continue

            # execute action
            action.perform( self, self.player )

            # handle enemy turns
            self.handle_enemy_turns()

            # update the FOV before the player's next action
            self.update_fov()

    # recompute the visible area based on the player's point of view
    def update_fov( self ) -> None:

        self.game_map.visible[:] = compute_fov(

            self.game_map.tiles[ "transparent" ],
            ( self.player.x, self.player.y ),
            radius =8
        )
        # if a tile is "visible" it should be added to "explored"
        self.game_map.explored |= self.game_map.visible
            
    # render the current frame to the screen
    def render( self, console: Console, context: Context ) -> None:

        # render the game map
        self.game_map.render( console )

        # present context
        context.present( console )

        # clear console
        console.clear()