# import dependencies
from typing import Set, Iterable, Any

from tcod.context import Context
from tcod.console import Console

from entity import Entity
from game_map import GameMap # type: ignore
from input_handlers import EventHandler

# manages the current state of the game
class Engine:

    # initialize engine with a set of entities, an event handler, and the player entity
    def __init__( self, entities: Set[ Entity ], event_handler: EventHandler, game_map: GameMap, player: Entity ):

        self.entities = entities
        self.event_handler = event_handler
        self.game_map = game_map
        self.player = player

    # handle events generated by the user
    def handle_events( self, events: Iterable[ Any ] ) -> None:

        # event loop
        for event in events:

            # initialize action with event handler
            action = self.event_handler.dispatch( event )

             # if no action is detected, continue
            if action is None:

                continue

            # execute action
            action.perform( self, self.player )
            
    # render the current frame to the screen
    def render( self, console: Console, context: Context ) -> None:

        # render the game map
        self.game_map.render( console )

        # step through each entity
        for entity in self.entities:

            # draw the entity to the console
            console.print( entity.x, entity.y, entity.char, fg=entity.color )

        # present context
        context.present( console )

        # clear console
        console.clear()